/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookRouteImport } from './routes/book'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicWaAvailabilityRouteImport } from './routes/api/public/wa/availability'
import { Route as ApiPublicWaBookRouteImport } from './routes/api/public/wa/book'
import { Route as ApiPublicWaCheckAvailabilityRouteImport } from './routes/api/public/wa/check-availability'
import { Route as ApiPublicWaLookupRouteImport } from './routes/api/public/wa/lookup'
import { Route as ApiPublicWaRemindersRouteImport } from './routes/api/public/wa/reminders'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicWaAvailabilityRoute = ApiPublicWaAvailabilityRouteImport.update({
  id: '/api/public/wa/availability',
  path: '/api/public/wa/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWaBookRoute = ApiPublicWaBookRouteImport.update({
  id: '/api/public/wa/book',
  path: '/api/public/wa/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWaCheckAvailabilityRoute =
  ApiPublicWaCheckAvailabilityRouteImport.update({
    id: '/api/public/wa/check-availability',
    path: '/api/public/wa/check-availability',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWaLookupRoute = ApiPublicWaLookupRouteImport.update({
  id: '/api/public/wa/lookup',
  path: '/api/public/wa/lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWaRemindersRoute = ApiPublicWaRemindersRouteImport.update({
  id: '/api/public/wa/reminders',
  path: '/api/public/wa/reminders',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/privacy': typeof PrivacyRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api/public/wa/availability': typeof ApiPublicWaAvailabilityRoute
  '/api/public/wa/book': typeof ApiPublicWaBookRoute
  '/api/public/wa/check-availability': typeof ApiPublicWaCheckAvailabilityRoute
  '/api/public/wa/lookup': typeof ApiPublicWaLookupRoute
  '/api/public/wa/reminders': typeof ApiPublicWaRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/privacy': typeof PrivacyRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api/public/wa/availability': typeof ApiPublicWaAvailabilityRoute
  '/api/public/wa/book': typeof ApiPublicWaBookRoute
  '/api/public/wa/check-availability': typeof ApiPublicWaCheckAvailabilityRoute
  '/api/public/wa/lookup': typeof ApiPublicWaLookupRoute
  '/api/public/wa/reminders': typeof ApiPublicWaRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/privacy': typeof PrivacyRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/api/public/wa/availability': typeof ApiPublicWaAvailabilityRoute
  '/api/public/wa/book': typeof ApiPublicWaBookRoute
  '/api/public/wa/check-availability': typeof ApiPublicWaCheckAvailabilityRoute
  '/api/public/wa/lookup': typeof ApiPublicWaLookupRoute
  '/api/public/wa/reminders': typeof ApiPublicWaRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/book'
    | '/contact'
    | '/faq'
    | '/gallery'
    | '/privacy'
    | '/reviews'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/api/public/wa/availability'
    | '/api/public/wa/book'
    | '/api/public/wa/check-availability'
    | '/api/public/wa/lookup'
    | '/api/public/wa/reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/book'
    | '/contact'
    | '/faq'
    | '/gallery'
    | '/privacy'
    | '/reviews'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/api/public/wa/availability'
    | '/api/public/wa/book'
    | '/api/public/wa/check-availability'
    | '/api/public/wa/lookup'
    | '/api/public/wa/reminders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/book'
    | '/contact'
    | '/faq'
    | '/gallery'
    | '/privacy'
    | '/reviews'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/admin'
    | '/api/public/wa/availability'
    | '/api/public/wa/book'
    | '/api/public/wa/check-availability'
    | '/api/public/wa/lookup'
    | '/api/public/wa/reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  PrivacyRoute: typeof PrivacyRoute
  ReviewsRoute: typeof ReviewsRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ApiPublicWaAvailabilityRoute: typeof ApiPublicWaAvailabilityRoute
  ApiPublicWaBookRoute: typeof ApiPublicWaBookRoute
  ApiPublicWaCheckAvailabilityRoute: typeof ApiPublicWaCheckAvailabilityRoute
  ApiPublicWaLookupRoute: typeof ApiPublicWaLookupRoute
  ApiPublicWaRemindersRoute: typeof ApiPublicWaRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/wa/availability': {
      id: '/api/public/wa/availability'
      path: '/api/public/wa/availability'
      fullPath: '/api/public/wa/availability'
      preLoaderRoute: typeof ApiPublicWaAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/wa/book': {
      id: '/api/public/wa/book'
      path: '/api/public/wa/book'
      fullPath: '/api/public/wa/book'
      preLoaderRoute: typeof ApiPublicWaBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/wa/check-availability': {
      id: '/api/public/wa/check-availability'
      path: '/api/public/wa/check-availability'
      fullPath: '/api/public/wa/check-availability'
      preLoaderRoute: typeof ApiPublicWaCheckAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/wa/lookup': {
      id: '/api/public/wa/lookup'
      path: '/api/public/wa/lookup'
      fullPath: '/api/public/wa/lookup'
      preLoaderRoute: typeof ApiPublicWaLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/wa/reminders': {
      id: '/api/public/wa/reminders'
      path: '/api/public/wa/reminders'
      fullPath: '/api/public/wa/reminders'
      preLoaderRoute: typeof ApiPublicWaRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  PrivacyRoute: PrivacyRoute,
  ReviewsRoute: ReviewsRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ApiPublicWaAvailabilityRoute: ApiPublicWaAvailabilityRoute,
  ApiPublicWaBookRoute: ApiPublicWaBookRoute,
  ApiPublicWaCheckAvailabilityRoute: ApiPublicWaCheckAvailabilityRoute,
  ApiPublicWaLookupRoute: ApiPublicWaLookupRoute,
  ApiPublicWaRemindersRoute: ApiPublicWaRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
